### ISSUE TITLE
Too many blanks in outline

### ISSUE THREAD

**Issue by super233** [Henning16/typora-gitbook-theme#1]
There's too many blanks  between different level of titles in outline, is there corresponding solution?

![image](https://user-images.githubusercontent.com/35358984/96357260-49d71e00-112c-11eb-9656-529f1529421a.png)

**Comment by Henning16** [comment]
Thanks for the feedback. Your issue has been in adressed in the [latest update](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.4.1).

**Comment by super233** [comment]
Thanks, it has been fixed. 👍
