### ISSUE TITLE
Graphical bug in the Themes Menu

### ISSUE THREAD

**Issue by Eike-Flath** [Henning16/typora-gitbook-theme#2]
There is a graphical bug in the Themes Menu of Typora which causes parts of the preview getting rendered above the checkmark.
![graphical bug](https://user-images.githubusercontent.com/65273694/96882481-a36a8000-147f-11eb-96f5-dac04af09b0f.png)

**Comment by Henning16** [comment]
Fixed issue in the [latest release](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5)
