### ISSUE TITLE
add tag before headers

### ISSUE THREAD

**Issue by chill-swift** [Henning16/typora-gitbook-theme#4]
awesome theme, we love it so much ~
could you pls add this little tag before headers, really helpful for us to add header on order, thx~

![image](https://user-images.githubusercontent.com/46042083/97064643-0a9c4780-15da-11eb-89c8-5e2622ca50f1.png)

**Comment by Henning16** [comment]
Hello, just to be clear, should the tag always be visible or just when the cursor is in the specific line?

**Comment by chill-swift** [comment]
> Hello, just to be clear, should the tag always be visible or just when the cursor is in the specific line?

![image](https://user-images.githubusercontent.com/46042083/97101002-87135100-16d4-11eb-907d-7d565e75037e.png)

Hi, henning16, thx for the reply.

just like this theme,  it could be always visible. (here is the link, if it helps: https://github.com/aCluelessDanny/typora-theme-ursine)

**Comment by Henning16** [comment]
Hi chill-swift, thx again for your feedback. I have added your suggestion to the [latest version](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.2). I hope you like it.

**Comment by chill-swift** [comment]
> Hi chill-swift, thx again for your feedback. I have added your suggestion to the [latest version](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.2). I hope you like it.

fabulous work!
thx a lot~

**Comment by malbiack** [comment]
I must say that the font format is amazing. But let me tell you that I prefer it to appear when the cursor passes over the title, as in the rest of the topics

**Comment by chill-swift** [comment]
> Hi chill-swift, thx again for your feedback. I have added your suggestion to the [latest version](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.2). I hope you like it.

![image](https://user-images.githubusercontent.com/46042083/97110530-bea1ed80-1714-11eb-9387-5b2121159703.png)
Hey, Henning16, I found the code here(I'm not a professional css user, sorry...), so, if other users want "when the cursor is in the specific line", maybe you could change it back, I can fix it by myself.

thx for all~

**Comment by malbiack** [comment]
> > Hi chill-swift, thx again for your feedback. I have added your suggestion to the [latest version](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.2). I hope you like it.
> 
> ![image](https://user-images.githubusercontent.com/46042083/97110530-bea1ed80-1714-11eb-9387-5b2121159703.png)
> Hey, Henning16, I found the code here(I'm not a professional css user, sorry...), so, if other users want "when the cursor is in the specific line", maybe you could change it back, I can fix it by myself.
> 
> thx for all~

At first glance you can see the difference between an H1 and an H2, H3, ..
Why do you need to see it always?

**Comment by Henning16** [comment]
I slightly prefer the variant, where the tag only shows up if the cursor is in the same line, too, like @malbiack said. I think I’m going to change it to that, but keep the overall look of the tags as they are right now.
