### ISSUE TITLE
Wish i can have a .docx output style file

### ISSUE THREAD

**Issue by DarckRM** [Henning16/typora-gitbook-theme#46]
Hello guys, recently my work need i write document in .docx, and i really like your typora theme work, so i was wondering, if you guys can support a .docx stylesheet file for Word, Thanks!

**Comment by h16nning** [comment]
Hello @DarckRM,
thank you for your interest in this theme! I'm really glad you like it! Sadly I have no experience in Word stylesheets and this theme is currently not at the top of my priority list. So unfortunately there won't be a word version of this theme in the near future :/
