### ISSUE TITLE
code line number display has overlap

### ISSUE THREAD

**Issue by SilenceX12138** [Henning16/typora-gitbook-theme#5]
As shown in the following graph, when the line number is greater than 10, with `gitbook theme` set as the default one, **open typora directly**, this phenomenon will appear.

However, after **switching into a different theme and switch back**, the problem will **disappear**.

![image](https://user-images.githubusercontent.com/47887520/99035048-b6bdc680-25b9-11eb-9090-384e2afadf48.png)
> Typora: 0.9.96

**Comment by Henning16** [comment]
Hello, I can´t reproduce the issue. Do you run typora on macOS, Windows or Linux?

**Comment by SilenceX12138** [comment]
> Hello, I can´t reproduce the issue. Do you run typora on macOS, Windows or Linux?

Windows 10

**Comment by Henning16** [comment]
I could reproduce a similar issue now once by changing the font size to a extremly big one. Could you tell me which font size your using?

**Comment by SilenceX12138** [comment]
The system display page zoom is 150% and the typora one is 120%.

**Comment by Henning16** [comment]
Hello,
I still cannot reproduce the issue under the specified circumstances. However, when changing the typora zoom to a very small one, the numbers start to overlap for me as well. I made some minor changes in the [latest release](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.5) which make those issues disappear on my PC. Could you check, if this does solve your problems?

**Comment by SilenceX12138** [comment]
![image](https://user-images.githubusercontent.com/47887520/99210113-e8c06a00-27ff-11eb-9fb1-551f69cc25bc.png)
thx~

It seems all right now!
