### ISSUE TITLE
What about diagram support?

### ISSUE THREAD

**Issue by enverarslan** [Henning16/typora-gitbook-theme#6]
Hello,

I think theme doesn't support [diagrams](https://support.typora.io/Draw-Diagrams-With-Markdown/). Default themes come with this feature. Can you add this?

Gitbook Azure Theme:
![image](https://user-images.githubusercontent.com/542179/99083948-550c5500-25d7-11eb-8b54-c9974f842d0e.png)

Github Theme:
![image](https://user-images.githubusercontent.com/542179/99084279-cd731600-25d7-11eb-82ef-a6721e4b8b06.png)

**Comment by Henning16** [comment]
Working on it...

**Comment by Henning16** [comment]
Seems like the color of the diagram is white so it is invsible.

**Comment by enverarslan** [comment]
@Henning16 Yes, there is proper html content in there. I think this is CSS problem.

**Comment by Henning16** [comment]
Hello @enverarslan, it should be fixed in [latest release](https://github.com/Henning16/typora-gitbook-theme/releases/tag/v1.5.4).
